apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: kuber-mon
  labels:
    app: grafana
spec:
  storageClassName: nfs-client-fast
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
