apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner-fast
  # replace with namespace where provisioner is deployed
  namespace: kuber-nfs
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-client-provisioner-runner-fast
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-client-provisioner-fast
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner-fast
    # replace with namespace where provisioner is deployed
    namespace: kuber-nfs
roleRef:
  kind: ClusterRole
  name: nfs-client-provisioner-runner-fast
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-client-provisioner-fast
  # replace with namespace where provisioner is deployed
  namespace: kuber-nfs
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-client-provisioner-fast
  # replace with namespace where provisioner is deployed
  namespace: kuber-nfs
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner-fast
    # replace with namespace where provisioner is deployed
    namespace: kuber-nfs
roleRef:
  kind: Role
  name: leader-locking-nfs-client-provisioner-fast
  apiGroup: rbac.authorization.k8s.io
